_inputs:
  ferris:
    type: image
    options:
      uploads_dir: img
  headshot:
    type: image
    options:
      uploads_dir: img

collections_config:
  people:
    _enabled_editors:
      - data
    image_key: headshot
    image_size: contain

_editables:
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    styles: /css/editor.css
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
